# optimizer/muon.yaml
optimizer:
  optimizer_mode: "muon"
  muon_lr: 0.02
  muon_momentum: 0.95
  muon_nesterov: true
  muon_ns_steps: 5

  # Set these to None since we're not using them
  sgd_lr: null
  momentum: null
  adamw_lr: null
  weight_decay: null
